apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    env: demo
spec:
    template:
        metadata:
            labels:     
                env: demo
            name: nginx
        spec:
            containers:
            - image: nginx
              name: nginx
    replicas: 3
    selector:
        matchLabels:
            env: demo
            
